apiVersion: 1

prune: true

datasources:
  - name: RouteForge Prometheus
    type: prometheus
    uid: routeforge-prometheus
    access: proxy
    url: http://127.0.0.1:9091
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
